openapi: 3.0.0
info:
  title: Task Management API
  version: 1.0.0
  description: A simple task management API for creating, updating, and deleting tasks, with JWT authentication.

servers:
  - url: http://localhost:5000
    description: Development server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /users/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  example: yourpassword
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User registered successfully.
        '400':
          description: Bad request
        '500':
          description: Internal Server Error

  /users/login:
    post:
      summary: Authenticate a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  example: yourpassword
      responses:
        '200':
          description: Successful authentication
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: your_jwt_token
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

  /users/verify-otp:
    post:
      summary: Verify OTP for account verification or password reset
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user@example.com
                otp:
                  type: string
                  example: "123456"
      responses:
        '200':
          description: OTP verified successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: OTP verified successfully.
        '400':
          description: Invalid OTP or request format
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: OTP verification failed, invalid OTP.
        '404':
          description: User not found
        '500':
          description: Internal Server Error

  /tasks:
    post:
      summary: Create a new task
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: New Task
                description:
                  type: string
                  example: Task description here.
                dueDate:
                  type: string
                  format: date-time
                  example: 2024-12-31T23:59:59Z
                priority:
                  type: string
                  enum: [low, medium, high]
                  example: medium
      responses:
        '201':
          description: Task created successfully
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

    get:
      summary: Get all tasks with pagination and filters
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            example: 1
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            example: 10
        - name: status
          in: query
          required: false
          schema:
            type: string
            example: completed
        - name: priority
          in: query
          required: false
          schema:
            type: string
            example: high
      responses:
        '200':
          description: Successfully retrieved tasks
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

  /tasks/{id}:
    get:
      summary: Get a task by ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Successfully retrieved task
        '401':
          description: Unauthorized
        '404':
          description: Task not found
        '500':
          description: Internal Server Error

    put:
      summary: Update a task by ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: Updated Task Title
                description:
                  type: string
                  example: Updated task description.
                dueDate:
                  type: string
                  format: date-time
                  example: 2024-12-31T23:59:59Z
                priority:
                  type: string
                  enum: [low, medium, high]
                  example: high
      responses:
        '200':
          description: Task updated successfully
        '401':
          description: Unauthorized
        '404':
          description: Task not found
        '500':
          description: Internal Server Error

    delete:
      summary: Delete a task by ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '204':
          description: Task deleted successfully
        '401':
          description: Unauthorized
        '404':
          description: Task not found
        '500':
          description: Internal Server Error

security:
  - bearerAuth: []
